name: autoupdate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */2 * *"
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Auto Update #Api调用
        run: |
          python ./.github/AUTO_UPDATE_SCRIPT/main.py README.md
      - name: Push to Git
        run : |
          git config user.email autoupdate@users.noreply.github.com
          git config user.name autoupdate
          git add README.md
          git commit -m "Auto Update"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
